package com.interswitch.voucherz.authservice.util;

public enum EventType {
    MERCHANT_CREATED,
    MERCHANT_LOGIN,
    MERCHANT_LOGOUT,
    VOUCHER_CREATED,
    VOUCHER_REDEEMED,
    CUSTOMER_CREATED,
    PRODUCT_CREATED,
    CAMPAIGN_CREATED,
    APPLICATION_CREATED,
    CUSTOMER_SEGMENT_CREATED,
    TOKEN_MANAGEMENT,
    FORGOT_PASSWORD,
    CHANGED_PASSWORD,
    CRUD_CUSTOMER,
    DELETE_CAMPAIGN
}
